project:
  type: website

website:
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Walk through the code"
        contents:
          - text: "🏠 Home"
            href: index.qmd
          - text: "🔵 See the code in R"
            href: r.qmd
          - icon: github
            text: "See the code on GitHub"
            href: https://github.com/posit-marketing/taylor-swift-tour
          - text: "☁️ Open the project in Posit Cloud"
    footer: spotify_playlist.html
  page-footer:
    center:
      - href: references.qmd
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/posit-software/
        aria-label: Posit LinkedIn
      - icon: mastodon
        href: https://fosstodon.org/@Posit
        aria-label: Posit Mastodon
      - icon: tiktok
        href: https://www.tiktok.com/@posit_pbc
        aria-label: Posit TikTok
      - icon: instagram
        href: https://www.instagram.com/posit.pbc/
        aria-label: Posit Instagram
        
execute:
  freeze: true

format:
  html:
    theme: cosmo
    mainfont: Lato
    css: style.css
    execute:
      echo: true
      eval: false
      fig-align: center
      message: false
      warning: false
    grid:
      sidebar-width: 300px
    include-in-header: 
      - progress-bar.html
    lightbox: auto
    page-layout: article
    toc: true
    toc-location: left
    toc-title: "Table of Contents"