project:
  type: website

website:
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Walk through the code"
        contents:
          - text: "🐍 See the code in Python"
            href: py.qmd
          - text: "🔵 See the code in R"
            href: r.qmd
          - text: "☁️ Open the project in Posit Cloud"
          - icon: github
            text: "See the code on GitHub"
    footer: spotify_playlist.html
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - href: appendix.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/posit-software/
        aria-label: Posit LinkedIn
      - icon: mastodon
        href: https://fosstodon.org/@Posit
        aria-label: Posit Mastodon
      - icon: tiktok
        href: https://www.tiktok.com/@posit_pbc
        aria-label: Posit TikTok
      - icon: instagram
        href: https://www.instagram.com/posit.pbc/
        aria-label: Posit Instagram
        
execute:
  freeze: true

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    toc-location: left
    toc-title: "Table of Contents"
    page-layout: full
    include-in-header: 
      - progress-bar.html
    lightbox: auto
    grid:
      sidebar-width: 300px