project:
  type: website

website:
  sidebar:
    style: "floating"
    search: false
    contents:
      - section: "Want to walk through the code?"
        contents:
          - text: "🐍 See the code in Python"
            href: py.qmd
          - text: "🔵 See the code in R"
            href: r.qmd
          - text: "☁️ Open the project in Posit Cloud"
          - icon: github
            text: "See the code on GitHub"

execute:
  freeze: true

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    toc-location: left
    toc-title: "Table of Contents"
    page-layout: full
    include-in-header: 
      - progress-bar.html
